title: Emacs Gifs
author: Jason Milkins
description: Bite sized chunks of Emacs in action

highlighter: pygments
permalink: /:title

url: https://emacsgifs.github.io/
baseurl: /

sass:
  sass_dir: public/css
  style: :compressed
