title: Emacs Gifs
author: Jason Milkins
description: Bite sized chunks of Emacs in action

highlighter: rouge
permalink: /:title

url:
baseurl:

sass:
  sass_dir: public/css
  style: :compressed

disqus: emacsgifs
